name: Sync Documentation to Outline Wiki

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - '**.md'
  workflow_dispatch:

jobs:
  sync-docs:
    name: Synchronizes Documentation
    runs-on: self-hosted
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: 'Sync documentation to Outline Wiki'
      uses: speedandfunction/docs-sync-action@main
      with:
        outline_token: ${{ secrets.OUTLINE_TOKEN }}
        outline_parent_document_id: ${{ vars.OUTLINE_PARENT_DOCUMENT_ID }}
        source_dir: './docs'
        verbose: 'true'
